/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dor_smarthome_app_sensors_types_dht11_DHT11Reader */

#ifndef _Included_com_dor_smarthome_app_sensors_types_dht11_DHT11Reader
#define _Included_com_dor_smarthome_app_sensors_types_dht11_DHT11Reader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dor_smarthome_app_sensors_types_dht11_DHT11Reader
 * Method:    getResponse
 * Signature: ()I
 */
JNIEXPORT jintArray JNICALL Java_com_dor_smarthome_app_sensors_types_dht11_DHT11Reader_getResponse
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
